steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=gcr.io/scaife-viewer/scaife-cts-api:$COMMIT_SHA
  - "."
images:
- gcr.io/scaife-viewer/scaife-cts-api:$COMMIT_SHA
timeout: 1200s
